-- ContractorHQ — Product Catalog: real Techo-Bloc Blu 60 / Blu Grande / Blu 80
-- product data, sourced from Techo-Bloc's official spec book (TechoSpec Handbook
-- Vol 26, page citations kept in specs.source per row). One-time data seed, not
-- schema — run AFTER 0036.
--
-- unit is 'sq ft' throughout — coverage_per_unit is set to 1 and
-- units_per_package to each row's sq_ft_per_pallet, so the Materials Sheet's
-- orderable-quantity nudge rounds an entered sq-ft quantity up to the next
-- whole pallet.

insert into public.product_catalog (manufacturer, category, name, sku, unit, specs) values
  ('Techo-Bloc', 'Pavers', 'Blu 60 Smooth — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'Smooth', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 116.82, 'sq_ft_per_layer', 10.62, 'pieces_per_pallet', null, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.39', 'notes', 'Piece count not tracked for modular/mixed bundles - multiple sizes per pallet makes a single count not meaningful', 'coverage_per_unit', 1, 'units_per_package', 116.82)),
  ('Techo-Bloc', 'Pavers', 'Blu 60 HD2 Smooth — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'HD2 Smooth', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 135.39, 'sq_ft_per_layer', 12.31, 'pieces_per_pallet', null, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.39', 'notes', 'NEW packaging (Eastern USA/Canada). Piece count not tracked for modular bundles.', 'coverage_per_unit', 1, 'units_per_package', 135.39)),
  ('Techo-Bloc', 'Pavers', 'Blu 60 Slate — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'Slate', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 116.82, 'sq_ft_per_layer', 10.62, 'pieces_per_pallet', null, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.38', 'notes', 'Piece count not tracked for modular bundles', 'coverage_per_unit', 1, 'units_per_package', 116.82)),
  ('Techo-Bloc', 'Pavers', 'Blu 60 HD2 Slate — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'HD2 Slate', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 135.39, 'sq_ft_per_layer', 12.31, 'pieces_per_pallet', null, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.38', 'notes', 'NEW packaging (Eastern USA) - updated from standard 116.82 sq ft. HD2 Slate only available in USA.', 'coverage_per_unit', 1, 'units_per_package', 135.39)),
  ('Techo-Bloc', 'Pavers', 'Blu 60 Polished — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'Polished', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '2 3/16 in (55mm)', 'sq_ft_per_pallet', 116.82, 'sq_ft_per_layer', 10.62, 'pieces_per_pallet', null, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.40', 'notes', 'Piece count not tracked for modular bundles', 'coverage_per_unit', 1, 'units_per_package', 116.82)),
  ('Techo-Bloc', 'Pavers', 'Blu 60 Smooth — 6x13 single size', null, 'sq ft', jsonb_build_object('size_bundle', '6x13 single size', 'finish', 'Smooth', 'unit_sizes', '6.5x13 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 116.05, 'sq_ft_per_layer', 10.55, 'pieces_per_pallet', 198, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.42', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 116.05)),
  ('Techo-Bloc', 'Pavers', 'Blu 60 HD2 Smooth — 6x13 single size', null, 'sq ft', jsonb_build_object('size_bundle', '6x13 single size', 'finish', 'HD2 Smooth', 'unit_sizes', '6.5x13 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 116.05, 'sq_ft_per_layer', 10.55, 'pieces_per_pallet', 198, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.42', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 116.05)),
  ('Techo-Bloc', 'Pavers', 'Blu 60 Slate — 6x13 single size', null, 'sq ft', jsonb_build_object('size_bundle', '6x13 single size', 'finish', 'Slate', 'unit_sizes', '6.5x13 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 116.05, 'sq_ft_per_layer', 10.55, 'pieces_per_pallet', 198, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.41', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 116.05)),
  ('Techo-Bloc', 'Pavers', 'Blu 60 HD2 Slate — 6x13 single size', null, 'sq ft', jsonb_build_object('size_bundle', '6x13 single size', 'finish', 'HD2 Slate', 'unit_sizes', '6.5x13 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 116.05, 'sq_ft_per_layer', 10.55, 'pieces_per_pallet', 198, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.41', 'notes', 'Single-size bundle - flat piece count is accurate. HD2 Slate only available in USA.', 'coverage_per_unit', 1, 'units_per_package', 116.05)),
  ('Techo-Bloc', 'Pavers', 'Blu Grande Slate — Single size (19.5x32.5in)', null, 'sq ft', jsonb_build_object('size_bundle', 'Single size (19.5x32.5in)', 'finish', 'Slate', 'unit_sizes', '19.5x32.5 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 87.91, 'sq_ft_per_layer', 8.79, 'pieces_per_pallet', 20, 'layers_per_pallet', 10, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.43', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 87.91)),
  ('Techo-Bloc', 'Pavers', 'Blu Grande HD2 Slate — Single size (19.5x32.5in)', null, 'sq ft', jsonb_build_object('size_bundle', 'Single size (19.5x32.5in)', 'finish', 'HD2 Slate', 'unit_sizes', '19.5x32.5 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 96.71, 'sq_ft_per_layer', 8.79, 'pieces_per_pallet', 22, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.43', 'notes', 'Single-size bundle - flat piece count is accurate. HD2 Slate only available in USA.', 'coverage_per_unit', 1, 'units_per_package', 96.71)),
  ('Techo-Bloc', 'Pavers', 'Blu Grande Smooth — Single size (19.5x32.5in)', null, 'sq ft', jsonb_build_object('size_bundle', 'Single size (19.5x32.5in)', 'finish', 'Smooth', 'unit_sizes', '19.5x32.5 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 87.91, 'sq_ft_per_layer', 8.79, 'pieces_per_pallet', 20, 'layers_per_pallet', 10, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.44', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 87.91)),
  ('Techo-Bloc', 'Pavers', 'Blu Grande HD2 Smooth — Single size (19.5x32.5in)', null, 'sq ft', jsonb_build_object('size_bundle', 'Single size (19.5x32.5in)', 'finish', 'HD2 Smooth', 'unit_sizes', '19.5x32.5 in', 'thickness', '2 3/8 in (60mm)', 'sq_ft_per_pallet', 96.71, 'sq_ft_per_layer', 8.79, 'pieces_per_pallet', 22, 'layers_per_pallet', 11, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.44', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 96.71)),
  ('Techo-Bloc', 'Pavers', 'Blu Grande Polished — Single size (19.5x32.5in)', null, 'sq ft', jsonb_build_object('size_bundle', 'Single size (19.5x32.5in)', 'finish', 'Polished', 'unit_sizes', '19.5x32.5 in', 'thickness', '2 3/16 in (55mm)', 'sq_ft_per_pallet', 87.91, 'sq_ft_per_layer', 8.79, 'pieces_per_pallet', 20, 'layers_per_pallet', 10, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.45', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 87.91)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 Slate — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'Slate', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '3 1/8 in (80mm)', 'sq_ft_per_pallet', 84.96, 'sq_ft_per_layer', 10.62, 'pieces_per_pallet', null, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.65', 'notes', 'Piece count not tracked for modular bundles. HD2 Slate only available in USA.', 'coverage_per_unit', 1, 'units_per_package', 84.96)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 HD2 Slate — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'HD2 Slate', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '3 1/8 in (80mm)', 'sq_ft_per_pallet', 84.96, 'sq_ft_per_layer', 10.62, 'pieces_per_pallet', null, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.65', 'notes', 'Piece count not tracked for modular bundles. HD2 Slate only available in USA.', 'coverage_per_unit', 1, 'units_per_package', 84.96)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 Smooth — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'Smooth', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '3 1/8 in (80mm)', 'sq_ft_per_pallet', 84.96, 'sq_ft_per_layer', 10.62, 'pieces_per_pallet', null, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.66', 'notes', 'Piece count not tracked for modular bundles', 'coverage_per_unit', 1, 'units_per_package', 84.96)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 HD2 Smooth — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'HD2 Smooth', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '3 1/8 in (80mm)', 'sq_ft_per_pallet', 84.96, 'sq_ft_per_layer', 10.62, 'pieces_per_pallet', null, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.66', 'notes', 'Piece count not tracked for modular bundles', 'coverage_per_unit', 1, 'units_per_package', 84.96)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 Polished — Modular (mixed)', null, 'sq ft', jsonb_build_object('size_bundle', 'Modular (mixed)', 'finish', 'Polished', 'unit_sizes', '6.5x13 in, 13x13 in, 19.5x13 in', 'thickness', '2 15/16 in (75mm)', 'sq_ft_per_pallet', 84.96, 'sq_ft_per_layer', 10.62, 'pieces_per_pallet', null, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.67', 'notes', 'Piece count not tracked for modular bundles', 'coverage_per_unit', 1, 'units_per_package', 84.96)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 Slate — 6x13 single size', null, 'sq ft', jsonb_build_object('size_bundle', '6x13 single size', 'finish', 'Slate', 'unit_sizes', '6.5x13 in', 'thickness', '3 1/8 in (80mm)', 'sq_ft_per_pallet', 84.40, 'sq_ft_per_layer', 10.55, 'pieces_per_pallet', 144, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.68', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 84.40)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 HD2 Slate — 6x13 single size', null, 'sq ft', jsonb_build_object('size_bundle', '6x13 single size', 'finish', 'HD2 Slate', 'unit_sizes', '6.5x13 in', 'thickness', '3 1/8 in (80mm)', 'sq_ft_per_pallet', 84.40, 'sq_ft_per_layer', 10.55, 'pieces_per_pallet', 144, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.68', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 84.40)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 Smooth — 6x13 single size', null, 'sq ft', jsonb_build_object('size_bundle', '6x13 single size', 'finish', 'Smooth', 'unit_sizes', '6.5x13 in', 'thickness', '3 1/8 in (80mm)', 'sq_ft_per_pallet', 84.40, 'sq_ft_per_layer', 10.55, 'pieces_per_pallet', 144, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.69', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 84.40)),
  ('Techo-Bloc', 'Pavers', 'Blu 80 HD2 Smooth — 6x13 single size', null, 'sq ft', jsonb_build_object('size_bundle', '6x13 single size', 'finish', 'HD2 Smooth', 'unit_sizes', '6.5x13 in', 'thickness', '3 1/8 in (80mm)', 'sq_ft_per_pallet', 84.40, 'sq_ft_per_layer', 10.55, 'pieces_per_pallet', 144, 'layers_per_pallet', 8, 'confidence', 'Confirmed - official spec book', 'source', 'TechoSpec Handbook Vol 26 p.69', 'notes', 'Single-size bundle - flat piece count is accurate', 'coverage_per_unit', 1, 'units_per_package', 84.40));
